/*
Copyright (c) 2012, The Environmental Council of the States (ECOS)
All rights reserved.
 
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
 
 * Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
 * Neither the name of the ECOS nor the names of its contributors may
   be used to endorse or promote products derived from this software
   without specific prior written permission.
 
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
*/
/*****************************************************************************************************************************   
 *
 *  Script Name:  ICIS_5.0-ORA-DDL-SYNONYMS-ICS_FLOW_LOCAL_USER.sql
 *
 *  Company:  Windsor Solutions, Inc.
 *  
 *  Purpose:  This script creates synonyms for all the objects owned by ICS_FLOW_LOCAL to ICS_FLOW_LOCAL_USER
 *   
 *  Maintenance:
 *  
 *    Analyst         Date            Comment 
 *    ----------      ----------      ------------------------------------------------------------------------------
 *    Windsor         09/10/2014      Created from 4.0 baseline.
 *    BRensmith       05/23/2012      Added synonym to new 5.0 database table ICS_SW_INDST_ANNUL_REP.
 *    KJames          10/03/2014      Added synonym for ICS_SUBSCTOR_CODE_PLUS_DESC.
 *    KJeffery        09/27/2016      Updates to support the ICIS 5.6 XML schema changes.
 *
 ****************************************************************************************************************************   
 */
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_ADDR FOR ICS_FLOW_LOCAL.ICS_ADDR;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_ANML_TYPE FOR ICS_FLOW_LOCAL.ICS_ANML_TYPE;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_ASSC_PRMT FOR ICS_FLOW_LOCAL.ICS_ASSC_PRMT;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_BASIC_PRMT FOR ICS_FLOW_LOCAL.ICS_BASIC_PRMT;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_BS_END_USE_DSPL_TYPE FOR ICS_FLOW_LOCAL.ICS_BS_END_USE_DSPL_TYPE;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_BS_PRMT FOR ICS_FLOW_LOCAL.ICS_BS_PRMT;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_BS_PROG_REP FOR ICS_FLOW_LOCAL.ICS_BS_PROG_REP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_BS_TYPE FOR ICS_FLOW_LOCAL.ICS_BS_TYPE;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_CAFO_ANNUL_REP FOR ICS_FLOW_LOCAL.ICS_CAFO_ANNUL_REP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_CAFO_INSP FOR ICS_FLOW_LOCAL.ICS_CAFO_INSP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_CAFO_INSP_VIOL_TYPE FOR ICS_FLOW_LOCAL.ICS_CAFO_INSP_VIOL_TYPE;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_CAFO_PRMT FOR ICS_FLOW_LOCAL.ICS_CAFO_PRMT;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_CMPL_INSP_TYPE FOR ICS_FLOW_LOCAL.ICS_CMPL_INSP_TYPE;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_CMPL_MON FOR ICS_FLOW_LOCAL.ICS_CMPL_MON;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_CMPL_MON_ACTN_REASON FOR ICS_FLOW_LOCAL.ICS_CMPL_MON_ACTN_REASON;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_CMPL_MON_AGNCY_TYPE FOR ICS_FLOW_LOCAL.ICS_CMPL_MON_AGNCY_TYPE;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_CMPL_MON_LNK FOR ICS_FLOW_LOCAL.ICS_CMPL_MON_LNK;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_CMPL_SCHD FOR ICS_FLOW_LOCAL.ICS_CMPL_SCHD;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_CMPL_SCHD_EVT FOR ICS_FLOW_LOCAL.ICS_CMPL_SCHD_EVT;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_CMPL_SCHD_EVT_VIOL_ELEM FOR ICS_FLOW_LOCAL.ICS_CMPL_SCHD_EVT_VIOL_ELEM;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_CMPL_SCHD_VIOL FOR ICS_FLOW_LOCAL.ICS_CMPL_SCHD_VIOL;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_CMPL_TRACK_STAT FOR ICS_FLOW_LOCAL.ICS_CMPL_TRACK_STAT;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_CONTACT FOR ICS_FLOW_LOCAL.ICS_CONTACT;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_CONTAINMENT FOR ICS_FLOW_LOCAL.ICS_CONTAINMENT;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_CO_DSPL_SITE FOR ICS_FLOW_LOCAL.ICS_CO_DSPL_SITE;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_CROP_TYPES_HARVESTED FOR ICS_FLOW_LOCAL.ICS_CROP_TYPES_HARVESTED;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_CROP_TYPES_PLANTED FOR ICS_FLOW_LOCAL.ICS_CROP_TYPES_PLANTED;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_CSO_EVT_REP FOR ICS_FLOW_LOCAL.ICS_CSO_EVT_REP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_CSO_INSP FOR ICS_FLOW_LOCAL.ICS_CSO_INSP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_CSO_PRMT FOR ICS_FLOW_LOCAL.ICS_CSO_PRMT;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_DMR_PROG_REP_LNK FOR ICS_FLOW_LOCAL.ICS_DMR_PROG_REP_LNK;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_DMR_VIOL FOR ICS_FLOW_LOCAL.ICS_DMR_VIOL;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_DSCH_MON_REP FOR ICS_FLOW_LOCAL.ICS_DSCH_MON_REP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_DSCH_MON_REP_PARAM_VIOL FOR ICS_FLOW_LOCAL.ICS_DSCH_MON_REP_PARAM_VIOL;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_DSCH_MON_REP_VIOL FOR ICS_FLOW_LOCAL.ICS_DSCH_MON_REP_VIOL;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_EFFLU_GUIDE FOR ICS_FLOW_LOCAL.ICS_EFFLU_GUIDE;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_EFFLU_TRADE_PRTNER FOR ICS_FLOW_LOCAL.ICS_EFFLU_TRADE_PRTNER;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_EFFLU_TRADE_PRTNER_ADDR FOR ICS_FLOW_LOCAL.ICS_EFFLU_TRADE_PRTNER_ADDR;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_ENFRC_ACTN_GOV_CONTACT FOR ICS_FLOW_LOCAL.ICS_ENFRC_ACTN_GOV_CONTACT;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_ENFRC_ACTN_MILESTONE FOR ICS_FLOW_LOCAL.ICS_ENFRC_ACTN_MILESTONE;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_ENFRC_ACTN_TYPE FOR ICS_FLOW_LOCAL.ICS_ENFRC_ACTN_TYPE;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_ENFRC_ACTN_VIOL_LNK FOR ICS_FLOW_LOCAL.ICS_ENFRC_ACTN_VIOL_LNK;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_ENFRC_AGNCY FOR ICS_FLOW_LOCAL.ICS_ENFRC_AGNCY;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_FAC FOR ICS_FLOW_LOCAL.ICS_FAC;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_FAC_CLASS FOR ICS_FLOW_LOCAL.ICS_FAC_CLASS;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_FINAL_ORDER FOR ICS_FLOW_LOCAL.ICS_FINAL_ORDER;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_FINAL_ORDER_PRMT_IDENT FOR ICS_FLOW_LOCAL.ICS_FINAL_ORDER_PRMT_IDENT;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_FINAL_ORDER_VIOL_LNK FOR ICS_FLOW_LOCAL.ICS_FINAL_ORDER_VIOL_LNK;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_FRML_ENFRC_ACTN FOR ICS_FLOW_LOCAL.ICS_FRML_ENFRC_ACTN;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_GEO_COORD FOR ICS_FLOW_LOCAL.ICS_GEO_COORD;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_GNRL_PRMT FOR ICS_FLOW_LOCAL.ICS_GNRL_PRMT;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_GPCF_CNST_WAIVER FOR ICS_FLOW_LOCAL.ICS_GPCF_CNST_WAIVER;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_GPCF_NOTICE_OF_INTENT FOR ICS_FLOW_LOCAL.ICS_GPCF_NOTICE_OF_INTENT;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_GPCF_NOTICE_OF_TERM FOR ICS_FLOW_LOCAL.ICS_GPCF_NOTICE_OF_TERM;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_GPCF_NO_EXPOSURE FOR ICS_FLOW_LOCAL.ICS_GPCF_NO_EXPOSURE;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_HIST_PRMT_SCHD_EVTS FOR ICS_FLOW_LOCAL.ICS_HIST_PRMT_SCHD_EVTS;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_IMPACT_SSO_EVT FOR ICS_FLOW_LOCAL.ICS_IMPACT_SSO_EVT;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_INCIN FOR ICS_FLOW_LOCAL.ICS_INCIN;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_INFRML_ENFRC_ACTN FOR ICS_FLOW_LOCAL.ICS_INFRML_ENFRC_ACTN;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_LAND_APPL_BMP FOR ICS_FLOW_LOCAL.ICS_LAND_APPL_BMP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_LAND_APPL_SITE FOR ICS_FLOW_LOCAL.ICS_LAND_APPL_SITE;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_LMT FOR ICS_FLOW_LOCAL.ICS_LMT;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_LMTS FOR ICS_FLOW_LOCAL.ICS_LMTS;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_LMT_SET FOR ICS_FLOW_LOCAL.ICS_LMT_SET;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_LMT_SET_MONTHS_APPL FOR ICS_FLOW_LOCAL.ICS_LMT_SET_MONTHS_APPL;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_LMT_SET_SCHD FOR ICS_FLOW_LOCAL.ICS_LMT_SET_SCHD;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_LMT_SET_STAT FOR ICS_FLOW_LOCAL.ICS_LMT_SET_STAT;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_LNK_BS_REP FOR ICS_FLOW_LOCAL.ICS_LNK_BS_REP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_LNK_CAFO_ANNUL_REP FOR ICS_FLOW_LOCAL.ICS_LNK_CAFO_ANNUL_REP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_LNK_CSO_EVT_REP FOR ICS_FLOW_LOCAL.ICS_LNK_CSO_EVT_REP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_LNK_ENFRC_ACTN FOR ICS_FLOW_LOCAL.ICS_LNK_ENFRC_ACTN;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_LNK_FEDR_CMPL_MON FOR ICS_FLOW_LOCAL.ICS_LNK_FEDR_CMPL_MON;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_LNK_LOC_LMTS_REP FOR ICS_FLOW_LOCAL.ICS_LNK_LOC_LMTS_REP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_LNK_PRETR_PERF_REP FOR ICS_FLOW_LOCAL.ICS_LNK_PRETR_PERF_REP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_LNK_SNGL_EVT FOR ICS_FLOW_LOCAL.ICS_LNK_SNGL_EVT;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_LNK_SSO_ANNUL_REP FOR ICS_FLOW_LOCAL.ICS_LNK_SSO_ANNUL_REP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_LNK_SSO_EVT_REP FOR ICS_FLOW_LOCAL.ICS_LNK_SSO_EVT_REP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_LNK_SSO_MONTHLY_EVT_REP FOR ICS_FLOW_LOCAL.ICS_LNK_SSO_MONTHLY_EVT_REP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_LNK_ST_CMPL_MON FOR ICS_FLOW_LOCAL.ICS_LNK_ST_CMPL_MON;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_LNK_SWMS_4_REP FOR ICS_FLOW_LOCAL.ICS_LNK_SWMS_4_REP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_LNK_SW_EVT_REP FOR ICS_FLOW_LOCAL.ICS_LNK_SW_EVT_REP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_LOC_LMTS FOR ICS_FLOW_LOCAL.ICS_LOC_LMTS;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_LOC_LMTS_POLUT FOR ICS_FLOW_LOCAL.ICS_LOC_LMTS_POLUT;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_LOC_LMTS_PROG_REP FOR ICS_FLOW_LOCAL.ICS_LOC_LMTS_PROG_REP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_MASTER_GNRL_PRMT FOR ICS_FLOW_LOCAL.ICS_MASTER_GNRL_PRMT;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_MNUR_LTTR_PRCSS_WW_STOR FOR ICS_FLOW_LOCAL.ICS_MNUR_LTTR_PRCSS_WW_STOR;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_MN_LMT_APPLIES FOR ICS_FLOW_LOCAL.ICS_MN_LMT_APPLIES;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_NAICS_CODE FOR ICS_FLOW_LOCAL.ICS_NAICS_CODE;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_NARR_COND_SCHD FOR ICS_FLOW_LOCAL.ICS_NARR_COND_SCHD;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_NAT_PRIO FOR ICS_FLOW_LOCAL.ICS_NAT_PRIO;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_NUM_COND FOR ICS_FLOW_LOCAL.ICS_NUM_COND;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_NUM_REP FOR ICS_FLOW_LOCAL.ICS_NUM_REP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_ORIG_PROGS FOR ICS_FLOW_LOCAL.ICS_ORIG_PROGS;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_OTHR_PRMTS FOR ICS_FLOW_LOCAL.ICS_OTHR_PRMTS;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_PARAM_LMTS FOR ICS_FLOW_LOCAL.ICS_PARAM_LMTS;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_PAYLOAD FOR ICS_FLOW_LOCAL.ICS_PAYLOAD;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_PLCY FOR ICS_FLOW_LOCAL.ICS_PLCY;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_POTW_PRMT FOR ICS_FLOW_LOCAL.ICS_POTW_PRMT;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_PRETR_INSP FOR ICS_FLOW_LOCAL.ICS_PRETR_INSP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_PRETR_PERF_SUMM FOR ICS_FLOW_LOCAL.ICS_PRETR_PERF_SUMM;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_PRETR_PRMT FOR ICS_FLOW_LOCAL.ICS_PRETR_PRMT;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_PRMT_COMP_TYPE FOR ICS_FLOW_LOCAL.ICS_PRMT_COMP_TYPE;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_PRMT_FEATR FOR ICS_FLOW_LOCAL.ICS_PRMT_FEATR;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_PRMT_FEATR_CHAR FOR ICS_FLOW_LOCAL.ICS_PRMT_FEATR_CHAR;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_PRMT_FEATR_TRTMNT_TYPE FOR ICS_FLOW_LOCAL.ICS_PRMT_FEATR_TRTMNT_TYPE;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_PRMT_IDENT FOR ICS_FLOW_LOCAL.ICS_PRMT_IDENT;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_PRMT_REISSU FOR ICS_FLOW_LOCAL.ICS_PRMT_REISSU;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_PRMT_SCHD_EVT FOR ICS_FLOW_LOCAL.ICS_PRMT_SCHD_EVT;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_PRMT_SCHD_EVT_VIOL_ELEM FOR ICS_FLOW_LOCAL.ICS_PRMT_SCHD_EVT_VIOL_ELEM;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_PRMT_SCHD_VIOL FOR ICS_FLOW_LOCAL.ICS_PRMT_SCHD_VIOL;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_PRMT_TERM FOR ICS_FLOW_LOCAL.ICS_PRMT_TERM;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_PRMT_TRACK_EVT FOR ICS_FLOW_LOCAL.ICS_PRMT_TRACK_EVT;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_PROG FOR ICS_FLOW_LOCAL.ICS_PROG;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_PROGS_VIOL FOR ICS_FLOW_LOCAL.ICS_PROGS_VIOL;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_PROJ_SRCS_FUND FOR ICS_FLOW_LOCAL.ICS_PROJ_SRCS_FUND;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_PROJ_TYPE FOR ICS_FLOW_LOCAL.ICS_PROJ_TYPE;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_REP_ANML_TYPE FOR ICS_FLOW_LOCAL.ICS_REP_ANML_TYPE;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_REP_PARAM FOR ICS_FLOW_LOCAL.ICS_REP_PARAM;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_RMVL_CRDTS FOR ICS_FLOW_LOCAL.ICS_RMVL_CRDTS;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_RMVL_CRDTS_POLUT FOR ICS_FLOW_LOCAL.ICS_RMVL_CRDTS_POLUT;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_SATL_COLL_SYSTM FOR ICS_FLOW_LOCAL.ICS_SATL_COLL_SYSTM;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_SCHD_EVT_VIOL FOR ICS_FLOW_LOCAL.ICS_SCHD_EVT_VIOL;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_SIC_CODE FOR ICS_FLOW_LOCAL.ICS_SIC_CODE;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_SNGL_EVTS_VIOL FOR ICS_FLOW_LOCAL.ICS_SNGL_EVTS_VIOL;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_SNGL_EVT_VIOL FOR ICS_FLOW_LOCAL.ICS_SNGL_EVT_VIOL;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_SSO_ANNUL_REP FOR ICS_FLOW_LOCAL.ICS_SSO_ANNUL_REP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_SSO_EVT_REP FOR ICS_FLOW_LOCAL.ICS_SSO_EVT_REP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_SSO_INSP FOR ICS_FLOW_LOCAL.ICS_SSO_INSP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_SSO_MONTHLY_EVT_REP FOR ICS_FLOW_LOCAL.ICS_SSO_MONTHLY_EVT_REP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_SSO_STPS FOR ICS_FLOW_LOCAL.ICS_SSO_STPS;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_SSO_SYSTM_COMP FOR ICS_FLOW_LOCAL.ICS_SSO_SYSTM_COMP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_SUBM_RESULTS FOR ICS_FLOW_LOCAL.ICS_SUBM_RESULTS;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_SUBM_TRACK FOR ICS_FLOW_LOCAL.ICS_SUBM_TRACK;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_SURF_DSPL_SITE FOR ICS_FLOW_LOCAL.ICS_SURF_DSPL_SITE;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_SWMS_4_LARGE_PRMT FOR ICS_FLOW_LOCAL.ICS_SWMS_4_LARGE_PRMT;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_SWMS_4_PROG_REP FOR ICS_FLOW_LOCAL.ICS_SWMS_4_PROG_REP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_SWMS_4_SMALL_PRMT FOR ICS_FLOW_LOCAL.ICS_SWMS_4_SMALL_PRMT;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_SW_CNST_INDST_INSP FOR ICS_FLOW_LOCAL.ICS_SW_CNST_INDST_INSP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_SW_CNST_INSP FOR ICS_FLOW_LOCAL.ICS_SW_CNST_INSP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_SW_CNST_NON_CNST_INSP FOR ICS_FLOW_LOCAL.ICS_SW_CNST_NON_CNST_INSP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_SW_CNST_PRMT FOR ICS_FLOW_LOCAL.ICS_SW_CNST_PRMT;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_SW_EVT_REP FOR ICS_FLOW_LOCAL.ICS_SW_EVT_REP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_SW_INDST_PRMT FOR ICS_FLOW_LOCAL.ICS_SW_INDST_PRMT;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_SW_MS_4_INSP FOR ICS_FLOW_LOCAL.ICS_SW_MS_4_INSP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_SW_NON_CNST_INSP FOR ICS_FLOW_LOCAL.ICS_SW_NON_CNST_INSP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_SW_UNPRMT_CNST_INSP FOR ICS_FLOW_LOCAL.ICS_SW_UNPRMT_CNST_INSP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_TELEPH FOR ICS_FLOW_LOCAL.ICS_TELEPH;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_UNPRMT_FAC FOR ICS_FLOW_LOCAL.ICS_UNPRMT_FAC;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_SW_INDST_ANNUL_REP FOR ICS_FLOW_LOCAL.ICS_SW_INDST_ANNUL_REP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_SUBSCTOR_CODE_PLUS_DESC FOR ICS_FLOW_LOCAL.ICS_SUBSCTOR_CODE_PLUS_DESC;

-- 5.6 changes
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_PROG_DEFCY_TYPE FOR ICS_FLOW_LOCAL.ICS_PROG_DEFCY_TYPE;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_SEP FOR ICS_FLOW_LOCAL.ICS_SEP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_REP_NON_CMPL_STAT FOR ICS_FLOW_LOCAL.ICS_REP_NON_CMPL_STAT;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_V_ANML_TYPE_HIB FOR ICS_FLOW_LOCAL.ICS_V_ANML_TYPE_HIB;

/* Synonym on the stored procedures */
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_DATA_PREP_MASTER FOR ICS_FLOW_LOCAL.ICS_DATA_PREP_MASTER;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_PROCESS_ACCEPTED_TRANS FOR ICS_FLOW_LOCAL.ICS_PROCESS_ACCEPTED_TRANS;

-- 5.8 changes
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_ANLYTCL_METHOD FOR ICS_FLOW_LOCAL.ICS_ANLYTCL_METHOD;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_BS_ANNUL_PROG_REP FOR ICS_FLOW_LOCAL.ICS_BS_ANNUL_PROG_REP;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_BS_MGMT_PRACTICES FOR ICS_FLOW_LOCAL.ICS_BS_MGMT_PRACTICES;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_CNST_SITE FOR ICS_FLOW_LOCAL.ICS_CNST_SITE;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_IMPAIRED_WTR_POLLUTANTS FOR ICS_FLOW_LOCAL.ICS_IMPAIRED_WTR_POLLUTANTS;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_MGMT_PRC_DEFCY_TYPE FOR ICS_FLOW_LOCAL.ICS_MGMT_PRC_DEFCY_TYPE;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_NPDES_DAT_GRP_NUM FOR ICS_FLOW_LOCAL.ICS_NPDES_DAT_GRP_NUM;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_PATHOGEN_REDUCTION_TYPE FOR ICS_FLOW_LOCAL.ICS_PATHOGEN_REDUCTION_TYPE;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_REP_OBLGTN_TYPE FOR ICS_FLOW_LOCAL.ICS_REP_OBLGTN_TYPE;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_TMDL_POLLUTANTS FOR ICS_FLOW_LOCAL.ICS_TMDL_POLLUTANTS;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_TMDL_POLUT FOR ICS_FLOW_LOCAL.ICS_TMDL_POLUT;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_TRTMNT_CHEMS_LIST FOR ICS_FLOW_LOCAL.ICS_TRTMNT_CHEMS_LIST;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_TRTMNT_PRCSS_TYPE FOR ICS_FLOW_LOCAL.ICS_TRTMNT_PRCSS_TYPE;
CREATE SYNONYM ICS_FLOW_LOCAL_USER.ICS_VECTOR_A_REDUCTION_TYPE FOR ICS_FLOW_LOCAL.ICS_VECTOR_A_REDUCTION_TYPE;

