CREATE SEQUENCE COLUMN_ID_SEQUENCE;

CREATE TABLE RCRA_ABSFEATUREPROPTYPE
(
	ID number(19) NOT NULL
		PRIMARY KEY
);

CREATE TABLE RCRA_AREAACREAGE
(
	ID                       number(19) NOT NULL
		PRIMARY KEY,
	AREAACREAGEMSR           number(13, 2),
	AREAMSRDATEITEM          date,
	AREAMSRSOURCECODE        varchar2(4 char),
	AREAMSRSOURCEDATOWNRCODE varchar2(2 char),
	AREAMSRSOURCETXT         varchar2(255 char)
);

CREATE TABLE RCRA_CERT
(
	ID                 number(19) NOT NULL
		PRIMARY KEY,
	CERTEMAILTXT       varchar2(80 char),
	CERTSEQNUMBER      number(8),
	FIRSTNAME          varchar2(38 char),
	INDIVIDUALTITLETXT varchar2(45 char),
	LASTNAME           varchar2(38 char),
	MIDDLEINITIAL      varchar2(1 char),
	SIGNEDDATEITEM     date,
	TRANSACTIONCODE    varchar2(1 char),
	HANDLERID          number(19)
);

CREATE TABLE RCRA_CITN
(
	ID                number(19) NOT NULL
		PRIMARY KEY,
	CITNDESC          varchar2(255 char),
	CITNNAME          varchar2(35 char),
	CITNNAMEOWNR      varchar2(2 char),
	CITNNAMESEQNUMBER number(6),
	CITNNAMETYPE      varchar2(2 char),
	NOTES             varchar2(2000 char),
	TRANSACTIONCODE   varchar2(1 char),
	VIOID             number(19)
);

CREATE TABLE RCRA_CMEFACSUB
(
	ID                number(19) NOT NULL
		PRIMARY KEY,
	EPAHANDLERID      varchar2(12 char),
	HZRDWASTECMESUBID number(19)
);

CREATE TABLE RCRA_CONTACT
(
	ID                 number(19) NOT NULL
		PRIMARY KEY,
	EMAILADDRESSTXT    varchar2(240 char),
	FAX                varchar2(15 char),
	FIRSTNAME          varchar2(38 char),
	INDIVIDUALTITLETXT varchar2(45 char),
	LASTNAME           varchar2(38 char),
	MIDDLEINITIAL      varchar2(1 char),
	ORGFORMALNAME      varchar2(80 char),
	PHONEEXTTXT        varchar2(6 char),
	TELEPHONE          varchar2(15 char)
);

CREATE TABLE RCRA_CONTACTADDRESS
(
	ID                   number(19) NOT NULL
		PRIMARY KEY,
	CONTACTADDRESSID     number(19)
		CONSTRAINT FK_FYY3OHQ10GA7NW3JPJCSOI796
		REFERENCES RCRA_CONTACT,
	MAILCONTACTADDRESSID number(19)
);

CREATE TABLE RCRA_CORRACTAREA
(
	ID                        number(19) NOT NULL
		PRIMARY KEY,
	EPARSPPERSONDATOWNRCODE   varchar2(255 char),
	EPARSPPERSONID            varchar2(255 char),
	AIRRELEASEIND             varchar2(1 char),
	AREANAME                  varchar2(40 char),
	AREASEQNUMBER             number(4),
	FACWIDEIND                varchar2(1 char),
	GROUNDWATERRELEASEIND     varchar2(1 char),
	REGULATEDUNITIND          varchar2(1 char),
	SOILRELEASEIND            varchar2(1 char),
	STATERSPPERSONDATOWNRCODE varchar2(255 char),
	STATERSPPERSONID          varchar2(255 char),
	SUPPINFTXT                varchar2(2000 char),
	SURFACEWATERRELEASEIND    varchar2(1 char),
	TRANSACTIONCODE           varchar2(1 char),
	CORRACTFACSUBID           number(19)
);

CREATE TABLE RCRA_CORRACTAUTH
(
	ID                        number(19) NOT NULL
		PRIMARY KEY,
	ACTLOCCODE                varchar2(255 char),
	AGENCYTXT                 varchar2(255 char),
	AUTHAGENCYCODE            varchar2(1 char),
	AUTHDATOWNRCODE           varchar2(2 char),
	AUTHEFFECTIVEDATEITEM     date,
	AUTHSUBORGCODE            varchar2(10 char),
	AUTHSUBORGDATOWNRCODE     varchar2(2 char),
	AUTHTYPECODE              varchar2(1 char),
	AUTHTYPETXT               varchar2(255 char),
	ENDDATEITEM               date,
	ESTABLISHEDREPOSITORYCODE varchar2(1 char),
	ESTABLISHEDREPOSITORYTXT  varchar2(255 char),
	ISSUEDATEITEM             date,
	RSPLEADPROGRAMID          varchar2(1 char),
	RSPLEADPROGRAMTXT         varchar2(255 char),
	RSPPERSONDATOWNRCODE      varchar2(2 char),
	RSPPERSONID               varchar2(5 char),
	SUPPINFTXT                varchar2(2000 char),
	TRANSACTIONCODE           varchar2(1 char),
	CORRACTFACSUBID           number(19)
);

CREATE TABLE RCRA_CORRACTEVENT
(
	ID                      number(19) NOT NULL
		PRIMARY KEY,
	ACTLOCCODE              varchar2(255 char),
	ACTUALDATEITEM          date,
	AGENCYTXT               varchar2(255 char),
	CORRACTEVENTCODE        varchar2(7 char),
	CORRACTEVENTDATOWNRCODE varchar2(2 char),
	CORRACTEVENTTXT         varchar2(255 char),
	EVENTAGENCYCODE         varchar2(1 char),
	EVENTSEQNUMBER          number(3),
	EVENTSUBORGCODE         varchar2(10 char),
	EVENTSUBORGDATOWNRCODE  varchar2(2 char),
	NEWSCHEDDATEITEM        date,
	ORIGSCHEDDATEITEM       date,
	RSPPERSONDATOWNRCODE    varchar2(2 char),
	RSPPERSONID             varchar2(5 char),
	SUPPINFTXT              varchar2(2000 char),
	TRANSACTIONCODE         varchar2(1 char),
	CORRACTFACSUBID         number(19)
);

CREATE TABLE RCRA_CORRACTFACSUB
(
	ID                 number(19) NOT NULL
		PRIMARY KEY,
	HANDLERID          varchar2(12 char),
	HZRDWASTECORRACTID number(19)
);

ALTER TABLE RCRA_CORRACTAREA
	ADD CONSTRAINT FK_OFVHDIPQMXI2T4JNV3SG1A666
FOREIGN KEY (CORRACTFACSUBID) REFERENCES RCRA_CORRACTFACSUB;

ALTER TABLE RCRA_CORRACTAUTH
	ADD CONSTRAINT FK_KH0V1DD2U8BLD8J7HLY7ACCVB
FOREIGN KEY (CORRACTFACSUBID) REFERENCES RCRA_CORRACTFACSUB;

ALTER TABLE RCRA_CORRACTEVENT
	ADD CONSTRAINT FK_8C4Q63TD7HVOLM1TB96PE7DXU
FOREIGN KEY (CORRACTFACSUBID) REFERENCES RCRA_CORRACTFACSUB;

CREATE TABLE RCRA_CORRACTRELEVENT
(
	ID                      number(19) NOT NULL
		PRIMARY KEY,
	ACTLOCCODE              varchar2(255 char),
	AGENCYTXT               varchar2(255 char),
	CORRACTEVENTCODE        varchar2(7 char),
	CORRACTEVENTDATOWNRCODE varchar2(2 char),
	CORRACTEVENTTXT         varchar2(255 char),
	EVENTAGENCYCODE         varchar2(1 char),
	EVENTSEQNUMBER          number(3),
	TRANSACTIONCODE         varchar2(1 char),
	CORRACTAUTHID           number(19)
		CONSTRAINT FK_H0AN7U3D08TA0CNJB3YECXU2P
		REFERENCES RCRA_CORRACTAUTH,
	CORRACTAREAID           number(19)
		CONSTRAINT FK_J2MCE7P63N3LCAJ2TD4XYAANY
		REFERENCES RCRA_CORRACTAREA
);

CREATE TABLE RCRA_CORRACTRELPERMITUNIT
(
	ID                  number(19) NOT NULL
		PRIMARY KEY,
	PERMITUNITSEQNUMBER number(4),
	TRANSACTIONCODE     varchar2(1 char),
	CORRACTAREAID       number(19)
		CONSTRAINT FK_OG2J5S5A6JQ770Q6XRE8OIB6Q
		REFERENCES RCRA_CORRACTAREA
);

CREATE TABLE RCRA_CORRACTSTATCITN
(
	ID                  number(19) NOT NULL
		PRIMARY KEY,
	STATCITNDATOWNRCODE varchar2(2 char),
	STATCITNDESC        varchar2(255 char),
	STATCITNID          varchar2(1 char),
	TRANSACTIONCODE     varchar2(1 char),
	CORRACTAUTHID       number(19)
		CONSTRAINT FK_OLEX4UMGYKUHMTSRWTKT2MG8R
		REFERENCES RCRA_CORRACTAUTH
);

CREATE TABLE RCRA_COSTEST
(
	ID                   number(19) NOT NULL
		PRIMARY KEY,
	ACTLOCCODE           varchar2(255 char),
	AGENCYTXT            varchar2(255 char),
	AREAUNITNOTESTXT     varchar2(240 char),
	COSTESTAGENCYCODE    varchar2(1 char),
	COSTESTAMT           number(13, 2),
	COSTESTDATEITEM      date,
	COSTESTREASONCODE    varchar2(1 char),
	COSTESTREASONTXT     varchar2(255 char),
	COSTESTSEQNUMBER     number(1),
	COSTESTTYPECODE      varchar2(1 char),
	COSTESTTYPETXT       varchar2(255 char),
	RSPPERSONDATOWNRCODE varchar2(2 char),
	RSPPERSONID          varchar2(5 char),
	SUPPINFTXT           varchar2(2000 char),
	TRANSACTIONCODE      varchar2(1 char),
	FINASSURFACSUBID     number(19)
);

CREATE TABLE RCRA_COSTESTRELMECH
(
	ID                  number(19) NOT NULL
		PRIMARY KEY,
	ACTLOCCODE          varchar2(255 char),
	AGENCYTXT           varchar2(255 char),
	MECHAGENCYCODE      varchar2(1 char),
	MECHDETAILSEQNUMBER number(4),
	MECHSEQNUMBER       number(4),
	TRANSACTIONCODE     varchar2(1 char),
	COSTESTID           number(19)
		CONSTRAINT FK_IRRH1V858R52P9ECEA3FRS0P1
		REFERENCES RCRA_COSTEST
);

CREATE TABLE RCRA_CSNYDATE
(
	ID              number(19) NOT NULL
		PRIMARY KEY,
	SNYDATEITEM     date,
	TRANSACTIONCODE varchar2(1 char),
	ENFRCACTID      number(19)
);

CREATE TABLE RCRA_ENFRCACT
(
	ID                          number(19) NOT NULL
		PRIMARY KEY,
	AGENCYTXT                   varchar2(255 char),
	APPEALINITIATEDDATEITEM     date,
	APPEALRESOLUTIONDATEITEM    date,
	CNSNTAGREEFINORDERSEQNUMBER number(6),
	CORRACTCOMPONENT            varchar2(1 char),
	DISPOSSTATUS                varchar2(2 char),
	DISPOSSTATUSDATEITEM        date,
	DISPOSSTATUSOWNR            varchar2(2 char),
	DISPOSSTATUSTXT             varchar2(255 char),
	ENFRCACTDATEITEM            date,
	ENFRCACTID                  varchar2(3 char),
	ENFRCAGENCYLOCNAME          varchar2(2 char),
	ENFRCAGENCYNAME             varchar2(1 char),
	ENFRCATTORNEY               varchar2(5 char),
	ENFRCDOCKETNUMBER           varchar2(15 char),
	ENFRCOWNR                   varchar2(2 char),
	ENFRCRSPPERSONID            varchar2(5 char),
	ENFRCRSPPERSONOWNR          varchar2(2 char),
	ENFRCRSPSUBORG              varchar2(10 char),
	ENFRCRSPSUBORGOWNR          varchar2(2 char),
	ENFRCTYPE                   varchar2(3 char),
	ENFRCTYPETXT                varchar2(255 char),
	NOTES                       varchar2(2000 char),
	RESPONDENTNAME              varchar2(255 char),
	TRANSACTIONCODE             varchar2(1 char),
	CMEFACSUBID                 number(19)
		CONSTRAINT FK_E1WU84K8RSSDY62XMUY5595B8
		REFERENCES RCRA_CMEFACSUB
);

ALTER TABLE RCRA_CSNYDATE
	ADD CONSTRAINT FK_P3E2X7O8GTIA4R4W748QN5YHA
FOREIGN KEY (ENFRCACTID) REFERENCES RCRA_ENFRCACT;

CREATE TABLE RCRA_ENVPERMIT
(
	ID                number(19) NOT NULL
		PRIMARY KEY,
	ENVPERMITDESC     varchar2(80 char),
	ENVPERMITID       varchar2(13 char),
	ENVPERMITOWNRNAME varchar2(2 char),
	ENVPERMITTYPECODE varchar2(1 char),
	ENVPERMITTYPETXT  varchar2(255 char),
	TRANSACTIONCODE   varchar2(1 char),
	HANDLERID         number(19)
);

CREATE TABLE RCRA_EVAL
(
	ID                  number(19) NOT NULL
		PRIMARY KEY,
	AGENCYTXT           varchar2(255 char),
	CTZNCOMPLAINTIND    varchar2(1 char),
	DAYZEROITEM         date,
	EVALACTLOC          varchar2(2 char),
	EVALID              varchar2(3 char),
	EVALRSPAGENCY       varchar2(1 char),
	EVALRSPPERSONID     varchar2(5 char),
	EVALRSPPERSONIDOWNR varchar2(2 char),
	EVALRSPSUBORG       varchar2(10 char),
	EVALRSPSUBORGOWNR   varchar2(2 char),
	EVALSTARTDATEITEM   date,
	EVALTYPE            varchar2(3 char),
	EVALTYPEOWNR        varchar2(2 char),
	EVALTYPETXT         varchar2(255 char),
	FOCUSAREA           varchar2(3 char),
	FOCUSAREAOWNR       varchar2(2 char),
	FOCUSAREATXT        varchar2(255 char),
	FOUNDVIO            varchar2(1 char),
	MEDIAIND            varchar2(1 char),
	NOTSUBTITLECIND     varchar2(1 char),
	NOTES               varchar2(2000 char),
	SAMPLINGIND         varchar2(1 char),
	TRANSACTIONCODE     varchar2(1 char),
	CMEFACSUBID         number(19)
		CONSTRAINT FK_O0TWWOKM7B8NCXLBU64WULTHB
		REFERENCES RCRA_CMEFACSUB
);

CREATE TABLE RCRA_EVALCOMMIT
(
	ID              number(19) NOT NULL
		PRIMARY KEY,
	COMMITLEAD      varchar2(2 char),
	COMMITSEQNUMBER number(6),
	TRANSACTIONCODE varchar2(1 char),
	EVALID          number(19)
		CONSTRAINT FK_1K8T5Y599OH0OA32WSDUJ35SN
		REFERENCES RCRA_EVAL
);

CREATE TABLE RCRA_EVALVIO
(
	ID              number(19) NOT NULL
		PRIMARY KEY,
	AGENCYTXT       varchar2(255 char),
	AGENCYDETERMVIO varchar2(1 char),
	TRANSACTIONCODE varchar2(1 char),
	VIOACTLOC       varchar2(2 char),
	VIOSEQNUMBER    number(4),
	EVALID          number(19)
		CONSTRAINT FK_M3DN0WGSN246HRI51SP0I1Q0Q
		REFERENCES RCRA_EVAL
);

CREATE TABLE RCRA_EVENTCOMMIT
(
	ID              number(19) NOT NULL
		PRIMARY KEY,
	COMMITLEAD      varchar2(2 char),
	COMMITSEQNUMBER number(6),
	TRANSACTIONCODE varchar2(1 char),
	PERMITEVENTID   number(19),
	CORRACTEVENTID  number(19)
		CONSTRAINT FK_RTE19YXHW2SD0VXI7SL9UOFQX
		REFERENCES RCRA_CORRACTEVENT
);

CREATE TABLE RCRA_FACOWNROPER
(
	ID                   number(19) NOT NULL
		PRIMARY KEY,
	CURRENTENDDATEITEM   date,
	CURRENTSTARTDATEITEM date,
	OWNROPERIND          varchar2(2 char),
	OWNROPERSEQNUMBER    number(4),
	OWNROPERSUPPINFTXT   varchar2(4000 char),
	OWNROPERTXT          varchar2(255 char),
	OWNROPERTYPECODE     varchar2(1 char),
	OWNROPERTYPETXT      varchar2(255 char),
	TRANSACTIONCODE      varchar2(1 char),
	FACOWNROPERID        number(19)
		CONSTRAINT FK_B3W04RGU0W6SRPH295EU0DPT6
		REFERENCES RCRA_CONTACTADDRESS,
	HANDLERID            number(19)
);

CREATE TABLE RCRA_FACSUB
(
	ID                    number(19) NOT NULL
		PRIMARY KEY,
	DATACCESSTXT          varchar2(255 char),
	FACREGISTRYID         varchar2(12 char),
	HANDLERID             varchar2(12 char),
	PUBUSEEXTRACTIND      varchar2(1 char),
	TRANSACTIONCODE       varchar2(1 char),
	HZRDWASTEHANDLERSUBID number(19)
);

CREATE TABLE RCRA_FINASSURFACSUB
(
	ID            number(19) NOT NULL
		PRIMARY KEY,
	HANDLERID     varchar2(12 char),
	FINASSURSUBID number(19)
);

ALTER TABLE RCRA_COSTEST
	ADD CONSTRAINT FK_G64FUC1MVXIW6CX4KTG95MCN1
FOREIGN KEY (FINASSURFACSUBID) REFERENCES RCRA_FINASSURFACSUB;

CREATE TABLE RCRA_FINASSURSUB
(
	ID number(19) NOT NULL
		PRIMARY KEY
);

ALTER TABLE RCRA_FINASSURFACSUB
	ADD CONSTRAINT FK_OULVUQ90VKMRU0UJXEGYE86B4
FOREIGN KEY (FINASSURSUBID) REFERENCES RCRA_FINASSURSUB;

CREATE TABLE RCRA_GEOGINF
(
	ID                  number(19) NOT NULL
		PRIMARY KEY,
	AREASEQNUMBER       number(4),
	GEOGINFOWNR         varchar2(2 char),
	GEOGINFSEQNUMBER    number(4),
	LOCCOMMENTSTXT      varchar2(2000 char),
	PERMITUNITSEQNUMBER number(4),
	TRANSACTIONCODE     varchar2(1 char),
	AREAACREAGEID       number(19)
		CONSTRAINT FK_5V6IBIYXN7OMUEGWFG5TSF2JQ
		REFERENCES RCRA_AREAACREAGE,
	GEOGMETAID          number(19),
	WHEREID             number(19),
	GISFACSUBID         number(19)
);

CREATE TABLE RCRA_GEOGINFSUB
(
	ID number(19) NOT NULL
		PRIMARY KEY
);

CREATE TABLE RCRA_GEOGMETA
(
	ID                             number(19) NOT NULL
		PRIMARY KEY,
	COORDDATSOURCECODE             varchar2(3 char),
	COORDDATSOURCEDATOWNRCODE      varchar2(2 char),
	COORDDATSOURCENAME             varchar2(255 char),
	DATCOLLDATEITEM                date,
	GEOGREFPOINTCODE               varchar2(3 char),
	GEOGREFPOINTDATOWNRCODE        varchar2(2 char),
	GEOGREFPOINTNAME               varchar2(255 char),
	GEOMTYPECODE                   varchar2(3 char),
	GEOMTYPEDATOWNRCODE            varchar2(2 char),
	GEOMTYPENAME                   varchar2(255 char),
	HORIZACCURACYMSR               number(6),
	HORIZCOLLMETHODCODE            varchar2(3 char),
	HORIZCOLLMETHODDATOWNRCODE     varchar2(2 char),
	HORIZCOLLMETHODNAME            varchar2(255 char),
	HORIZCOORDREFSYSDATCODE        varchar2(3 char),
	HORIZCOORDREFSYSDATDATOWNRCODE varchar2(2 char),
	HORIZCOORDREFSYSDATUM          varchar2(255 char),
	SOURCEMAPSCALE                 number(10, 10),
	VERMETHODCODE                  varchar2(3 char),
	VERMETHODDATOWNRCODE           varchar2(2 char),
	VERMETHODNAME                  varchar2(255 char)
);

ALTER TABLE RCRA_GEOGINF
	ADD CONSTRAINT FK_2OTI6HOK7M07TM9IJ83R9RRNC
FOREIGN KEY (GEOGMETAID) REFERENCES RCRA_GEOGMETA;

CREATE TABLE RCRA_GISFACSUB
(
	ID          number(19) NOT NULL
		PRIMARY KEY,
	HANDLERID   varchar2(12 char),
	GEOINFSUBID number(19)
		CONSTRAINT FK_6ESUCAUCJP5WL5LKI3FQN2P0G
		REFERENCES RCRA_GEOGINFSUB
);

ALTER TABLE RCRA_GEOGINF
	ADD CONSTRAINT FK_OS8LW6L4H8SRCBEVXVD59RTG1
FOREIGN KEY (GISFACSUBID) REFERENCES RCRA_GISFACSUB;

CREATE TABLE RCRA_HANDLER
(
	ID                        number(19) NOT NULL
		PRIMARY KEY,
	ACCESSIBILITYCODE         varchar2(1 char),
	ACCESSIBILITYCODETXT      varchar2(255 char),
	ACKRECEIPTDATEITEM        date,
	ACTLOCCODE                varchar2(255 char),
	COUNTYCODE                varchar2(5 char),
	COUNTYCODEOWNR            varchar2(2 char),
	COUNTYNAME                varchar2(255 char),
	HANDLERINTERNALSUPPINFTXT varchar2(4000 char),
	HANDLERNAME               varchar2(80 char),
	HANDLERSUPPINFTXT         varchar2(4000 char),
	NATUREOFBUSINESSTXT       varchar2(4000 char),
	NONNOTIFIERIND            varchar2(1 char),
	NONNOTIFIERINDTXT         varchar2(255 char),
	OFFSITEWASTERECEIPTCODE   varchar2(1 char),
	RECEIVEDATEITEM           date,
	SHORTTERMSUPPINFTXT       varchar2(4000 char),
	SOURCERECSEQNUMBER        number(6),
	SOURCETYPECODE            varchar2(1 char),
	SOURCETYPETXT             varchar2(255 char),
	TRANSACTIONCODE           varchar2(1 char),
	TRTMNTSTORAGEDISPDATEITEM date,
	CONTACTADDRESSID          number(19)
		CONSTRAINT FK_HSW2L53MBIO8RBU46YGWLOJXY
		REFERENCES RCRA_CONTACTADDRESS,
	WASTEGENRTRID             number(19),
	HZRDSECONDARYMTRLID       number(19),
	LABHZRDWASTEID            number(19),
	LOCADDRESSID              number(19),
	MAILINGADDRESSID          number(19),
	PERMITCONTACTADDRESSID    number(19)
		CONSTRAINT FK_9W9JII4A7IS9JDBK4QDUNYS2D
		REFERENCES RCRA_CONTACTADDRESS,
	STATEWASTEGENRTRID        number(19),
	USEDOILID                 number(19),
	SITEWASTEACTID            number(19),
	FACSUBID                  number(19)
		CONSTRAINT FK_EPQKD49D8DXJ6AF5TPFLU30BD
		REFERENCES RCRA_FACSUB
);

ALTER TABLE RCRA_CERT
	ADD CONSTRAINT FK_OFRNDSNPIQPYAK8LX0X0LPEN6
FOREIGN KEY (HANDLERID) REFERENCES RCRA_HANDLER;

ALTER TABLE RCRA_ENVPERMIT
	ADD CONSTRAINT FK_FICN8LFT4FWCNAR552XFT4CDF
FOREIGN KEY (HANDLERID) REFERENCES RCRA_HANDLER;

ALTER TABLE RCRA_FACOWNROPER
	ADD CONSTRAINT FK_FC0RUWBL3PWYP6SW3EBORW1L2
FOREIGN KEY (HANDLERID) REFERENCES RCRA_HANDLER;

CREATE TABLE RCRA_HANDLERWASTECODE
(
	ID                     number(19) NOT NULL
		PRIMARY KEY,
	TRANSACTIONCODE        varchar2(1 char),
	WASTECODE              varchar2(6 char),
	WASTECODEOWNRNAME      varchar2(2 char),
	WASTECODETXT           varchar2(255 char),
	HZRDSECONDARYMTRLACTID number(19),
	HANDLERID              number(19)
		CONSTRAINT FK_705RBVPM0JFVL4O4UYUASJ49J
		REFERENCES RCRA_HANDLER,
	PERMITUNITDETAILID     number(19)
);

CREATE TABLE RCRA_HZRDSECONDARYMTRL
(
	ID                     number(19) NOT NULL
		PRIMARY KEY,
	EFFECTIVEDATEITEM      date,
	FINASSURIND            varchar2(1 char),
	NOTIFICATIONREASONCODE varchar2(1 char),
	NOTIFICATIONREASONTXT  varchar2(255 char),
	RECYCLINGIND           varchar2(1 char),
	TRANSACTIONCODE        varchar2(1 char)
);

ALTER TABLE RCRA_HANDLER
	ADD CONSTRAINT FK_NMYHIYSH92ET2D2PVQ3LG3B94
FOREIGN KEY (HZRDSECONDARYMTRLID) REFERENCES RCRA_HZRDSECONDARYMTRL;

CREATE TABLE RCRA_HZRDSECONDARYMTRLACT
(
	ID                      number(19) NOT NULL
		PRIMARY KEY,
	HSMSEQNUMBER            varchar2(4 char),
	ACTUALSHORTTONSQUANT    number(20, 10),
	ESTIMATEDSHORTTONSQUANT number(20, 10),
	FACCODEOWNRNAME         varchar2(2 char),
	FACTYPECODE             varchar2(2 char),
	FACTYPETXT              varchar2(255 char),
	LANDBASEDUNITIND        varchar2(2 char),
	LANDBASEDUNITINDTXT     varchar2(255 char),
	TRANSACTIONCODE         varchar2(1 char),
	HZRDSECONDARYMTRLID     number(19)
		CONSTRAINT FK_2XO41WB44PH0ALSDNJ14DM78Y
		REFERENCES RCRA_HZRDSECONDARYMTRL
);

ALTER TABLE RCRA_HANDLERWASTECODE
	ADD CONSTRAINT FK_889VS7KIAV7R3HSGTKEC3F3D4
FOREIGN KEY (HZRDSECONDARYMTRLACTID) REFERENCES RCRA_HZRDSECONDARYMTRLACT;

CREATE TABLE RCRA_HZRDWASTECMESUB
(
	ID number(19) NOT NULL
		PRIMARY KEY
);

ALTER TABLE RCRA_CMEFACSUB
	ADD CONSTRAINT FK_XVYKDQ5FLP51OOIDXFYV2FTN
FOREIGN KEY (HZRDWASTECMESUBID) REFERENCES RCRA_HZRDWASTECMESUB;

CREATE TABLE RCRA_HZRDWASTECORRACT
(
	ID number(19) NOT NULL
		PRIMARY KEY
);

ALTER TABLE RCRA_CORRACTFACSUB
	ADD CONSTRAINT FK_36E8AFV7VF5Q2FXVPIKT3OM2T
FOREIGN KEY (HZRDWASTECORRACTID) REFERENCES RCRA_HZRDWASTECORRACT;

CREATE TABLE RCRA_HZRDWASTEHANDLERSUB
(
	ID number(19) NOT NULL
		PRIMARY KEY
);

ALTER TABLE RCRA_FACSUB
	ADD CONSTRAINT FK_87I3IUEIFVR0SRWRSJ0A3DXLT
FOREIGN KEY (HZRDWASTEHANDLERSUBID) REFERENCES RCRA_HZRDWASTEHANDLERSUB;

CREATE TABLE RCRA_HZRDWASTEPERMIT
(
	ID number(19) NOT NULL
		PRIMARY KEY
);

CREATE TABLE RCRA_LABHZRDWASTE
(
	ID            number(19) NOT NULL
		PRIMARY KEY,
	COLLEGEIND    varchar2(1 char),
	HOSPITALIND   varchar2(1 char),
	NONPROFITIND  varchar2(1 char),
	WITHDRAWALIND varchar2(1 char)
);

ALTER TABLE RCRA_HANDLER
	ADD CONSTRAINT FK_52UE4N4158VTBYGLJO8XJ3FI4
FOREIGN KEY (LABHZRDWASTEID) REFERENCES RCRA_LABHZRDWASTE;

CREATE TABLE RCRA_LOCADDRESS
(
	ID            number(19) NOT NULL
		PRIMARY KEY,
	COUNTRYNAME   varchar2(2 char),
	LOCALITYNAME  varchar2(25 char),
	LOCADDRESS    varchar2(12 char),
	LOCADDRESSTXT varchar2(50 char),
	LOCZIPCODE    varchar2(14 char),
	STATEUSPSCODE varchar2(2 char),
	SUPPLOCTXT    varchar2(50 char)
);

ALTER TABLE RCRA_HANDLER
	ADD CONSTRAINT FK_BKXSSP2MOIKNIH7A63AAT03QH
FOREIGN KEY (LOCADDRESSID) REFERENCES RCRA_LOCADDRESS;

CREATE TABLE RCRA_MAILINGADDRESS
(
	ID                          number(19) NOT NULL
		PRIMARY KEY,
	MAILINGADDRESSCITYNAME      varchar2(25 char),
	MAILINGADDRESSCOUNTRYNAME   varchar2(2 char),
	MAILINGADDRESS              varchar2(12 char),
	MAILINGADDRESSSTATEUSPSCODE varchar2(2 char),
	MAILINGADDRESSTXT           varchar2(50 char),
	MAILINGADDRESSZIPCODE       varchar2(14 char),
	SUPPADDRESSTXT              varchar2(50 char)
);

ALTER TABLE RCRA_CONTACTADDRESS
	ADD CONSTRAINT FK_PK3T1VYHEBG5OPI6O894K4X2A
FOREIGN KEY (MAILCONTACTADDRESSID) REFERENCES RCRA_MAILINGADDRESS;

ALTER TABLE RCRA_HANDLER
	ADD CONSTRAINT FK_SNYP5O2GI3JBLLKLND6EQ7TV7
FOREIGN KEY (MAILINGADDRESSID) REFERENCES RCRA_MAILINGADDRESS;

CREATE TABLE RCRA_MECH
(
	ID                      number(19) NOT NULL
		PRIMARY KEY,
	ACTLOCCODE              varchar2(255 char),
	AGENCYTXT               varchar2(255 char),
	MECHAGENCYCODE          varchar2(1 char),
	MECHSEQNUMBER           number(4),
	MECHTYPECODE            varchar2(1 char),
	MECHTYPEDATOWNRCODE     varchar2(2 char),
	MECHTYPETXT             varchar2(255 char),
	PROVIDERFULLCONTACTNAME varchar2(33 char),
	PROVIDERTXT             varchar2(80 char),
	SUPPINFTXT              varchar2(2000 char),
	TELEPHONE               varchar2(15 char),
	TRANSACTIONCODE         varchar2(1 char),
	FINASSURFACSUBID        number(19)
		CONSTRAINT FK_LPV6CUW9TGHSN5F2FOWO184GF
		REFERENCES RCRA_FINASSURFACSUB
);

CREATE TABLE RCRA_MECHDETAIL
(
	ID                    number(19) NOT NULL
		PRIMARY KEY,
	EFFECTIVEDATEITEM     date,
	EXPIRATIONDATEITEM    date,
	FACEVALAMT            number(13, 2),
	MECHDETAILSEQNUMBER   number(4),
	MECHIDENTIFICATIONTXT varchar2(40 char),
	SUPPINFTXT            varchar2(2000 char),
	TRANSACTIONCODE       varchar2(1 char),
	MECHID                number(19)
		CONSTRAINT FK_CC5V9FXBVLBWP8XN9PQI4HDCA
		REFERENCES RCRA_MECH
);

CREATE TABLE RCRA_MEDIA
(
	ID              number(19) NOT NULL
		PRIMARY KEY,
	MEDIACODE       varchar2(3 char),
	MEDIACODEOWNR   varchar2(2 char),
	NOTES           varchar2(2000 char),
	TRANSACTIONCODE varchar2(1 char),
	ENFRCACTID      number(19)
		CONSTRAINT FK_4P6J3PRC7VRLNA9S1GNIBWUOA
		REFERENCES RCRA_ENFRCACT
);

CREATE TABLE RCRA_MLSTN
(
	ID                       number(19) NOT NULL
		PRIMARY KEY,
	MLSTNACTUALCMPLTDATEITEM date,
	MLSTNDEFAULTEDDATEITEM   date,
	MLSTNSCHEDCMPLTDATEITEM  date,
	MLSTNSEQNUMBER           number(6),
	NOTES                    varchar2(2000 char),
	TECHREQDESC              varchar2(200 char),
	TECHREQID                varchar2(50 char),
	TRANSACTIONCODE          varchar2(1 char),
	ENFRCACTID               number(19)
		CONSTRAINT FK_GQO05CGINRHUG2K2I8UA70NYD
		REFERENCES RCRA_ENFRCACT
);

CREATE TABLE RCRA_NAICS
(
	ID              number(19) NOT NULL
		PRIMARY KEY,
	NAICSCODE       varchar2(6 char),
	NAICSOWNRCODE   varchar2(2 char),
	NAICSSEQNUMBER  varchar2(4 char),
	NAICSTXT        varchar2(255 char),
	TRANSACTIONCODE varchar2(1 char),
	HANDLERID       number(19)
		CONSTRAINT FK_1H6RHAK8YG4SPW1JJNWI71VVV
		REFERENCES RCRA_HANDLER
);

CREATE TABLE RCRA_OTHERID
(
	ID                number(19) NOT NULL
		PRIMARY KEY,
	OTHERHANDLERID    varchar2(12 char),
	OTHERIDSUPPINFTXT varchar2(4000 char),
	RELOWNRNAME       varchar2(2 char),
	RELTYPECODE       varchar2(1 char),
	RELTYPETXT        varchar2(255 char),
	SAMEFACIND        varchar2(1 char),
	TRANSACTIONCODE   varchar2(1 char),
	FACSUBID          number(19)
		CONSTRAINT FK_NI1EPM1DPA46EGMGVSXGRLML8
		REFERENCES RCRA_FACSUB
);

CREATE TABLE RCRA_PAYMNT
(
	ID                      number(19) NOT NULL
		PRIMARY KEY,
	ACTUALPAIDAMT           number(13, 2),
	ACTUALPAYMNTDATEITEM    date,
	NOTES                   varchar2(2000 char),
	PAYMNTDEFAULTEDDATEITEM date,
	PAYMNTSEQNUMBER         number(2),
	SCHEDPAYMNTAMT          number(13, 2),
	SCHEDPAYMNTDATEITEM     date,
	TRANSACTIONCODE         varchar2(1 char),
	PENALTYID               number(19)
);

CREATE TABLE RCRA_PENALTY
(
	ID                        number(19) NOT NULL
		PRIMARY KEY,
	CASHCIVILPENALTYSOUGHTAMT number(13, 2),
	NOTES                     varchar2(2000 char),
	PENALTYTYPE               varchar2(3 char),
	PENALTYTYPEOWNR           varchar2(2 char),
	PENALTYTYPETXT            varchar2(255 char),
	TRANSACTIONCODE           varchar2(1 char),
	ENFRCACTID                number(19)
		CONSTRAINT FK_9KCFD847TWYOHQCIV7LVE2CLA
		REFERENCES RCRA_ENFRCACT
);

ALTER TABLE RCRA_PAYMNT
	ADD CONSTRAINT FK_5FVCS8S7NSRIRDI45M2DEV18S
FOREIGN KEY (PENALTYID) REFERENCES RCRA_PENALTY;

CREATE TABLE RCRA_PERMITEVENT
(
	ID                     number(19) NOT NULL
		PRIMARY KEY,
	ACTLOCCODE             varchar2(255 char),
	ACTUALDATEITEM         date,
	AGENCYTXT              varchar2(255 char),
	EVENTAGENCYCODE        varchar2(1 char),
	EVENTSEQNUMBER         number(3),
	EVENTSUBORGCODE        varchar2(10 char),
	EVENTSUBORGDATOWNRCODE varchar2(2 char),
	NEWSCHEDDATEITEM       date,
	ORIGSCHEDDATEITEM      date,
	PERMITEVENTCODE        varchar2(7 char),
	PERMITEVENTDATOWNRCODE varchar2(2 char),
	PERMITEVENTTXT         varchar2(255 char),
	RSPPERSONDATOWNRCODE   varchar2(2 char),
	RSPPERSONID            varchar2(5 char),
	SUPPINFTXT             varchar2(2000 char),
	TRANSACTIONCODE        varchar2(1 char),
	PERMITSERIESID         number(19)
);

ALTER TABLE RCRA_EVENTCOMMIT
	ADD CONSTRAINT FK_3W6B53PWU60ADYRULPG11E4UC
FOREIGN KEY (PERMITEVENTID) REFERENCES RCRA_PERMITEVENT;

CREATE TABLE RCRA_PERMITFACSUB
(
	ID                number(19) NOT NULL
		PRIMARY KEY,
	HANDLERID         varchar2(12 char),
	HZRDWASTEPERMITID number(19)
		CONSTRAINT FK_P33A7OPY9EPVHU4KB5WBL0BGR
		REFERENCES RCRA_HZRDWASTEPERMIT
);

CREATE TABLE RCRA_PERMITRELEVENT
(
	ID                     number(19) NOT NULL
		PRIMARY KEY,
	ACTLOCCODE             varchar2(255 char),
	AGENCYTXT              varchar2(255 char),
	EVENTAGENCYCODE        varchar2(1 char),
	EVENTSEQNUMBER         number(3),
	PERMITEVENTCODE        varchar2(7 char),
	PERMITEVENTDATOWNRCODE varchar2(2 char),
	PERMITEVENTTXT         varchar2(255 char),
	PERMITSERIESSEQNUMBER  number(4),
	TRANSACTIONCODE        varchar2(1 char),
	PERMITUNITDETAILID     number(19)
);

CREATE TABLE RCRA_PERMITSERIES
(
	ID                    number(19) NOT NULL
		PRIMARY KEY,
	PERMITSERIESNAME      varchar2(40 char),
	PERMITSERIESSEQNUMBER number(4),
	RSPPERSONDATOWNRCODE  varchar2(2 char),
	RSPPERSONID           varchar2(5 char),
	SUPPINFTXT            varchar2(2000 char),
	TRANSACTIONCODE       varchar2(1 char),
	PERMITFACSUBID        number(19)
		CONSTRAINT FK_GEQ5FCCYHRFO95CQ1D8BCAQ57
		REFERENCES RCRA_PERMITFACSUB
);

ALTER TABLE RCRA_PERMITEVENT
	ADD CONSTRAINT FK_HBHNLMWDW7D5LLMLLFN9USPAP
FOREIGN KEY (PERMITSERIESID) REFERENCES RCRA_PERMITSERIES;

CREATE TABLE RCRA_PERMITUNIT
(
	ID                  number(19) NOT NULL
		PRIMARY KEY,
	PERMITUNITNAME      varchar2(40 char),
	PERMITUNITSEQNUMBER number(4),
	SUPPINFTXT          varchar2(2000 char),
	TRANSACTIONCODE     varchar2(1 char),
	PERMITFACSUBID      number(19)
		CONSTRAINT FK_5D4UWJLMPUOXLKC1P67QG2XH4
		REFERENCES RCRA_PERMITFACSUB
);

CREATE TABLE RCRA_PERMITUNITDETAIL
(
	ID                            number(19) NOT NULL
		PRIMARY KEY,
	CAPTYPECODE                   varchar2(1 char),
	CAPTYPETXT                    varchar2(255 char),
	COMMERCIALSTATUSCODE          varchar2(1 char),
	COMMERCIALSTATUSTXT           varchar2(255 char),
	LEGALOPERSTATUSCODE           varchar2(4 char),
	LEGALOPERSTATUSDATOWNRCODE    varchar2(2 char),
	LEGALOPERSTATUSTXT            varchar2(255 char),
	MSRUNITCODE                   varchar2(1 char),
	MSRUNITDATOWNRCODE            varchar2(2 char),
	MSRUNITTXT                    varchar2(255 char),
	NUMBEROFUNITSCOUNT            number(7),
	PERMITSTATUSEFFECTIVEDATEITEM date,
	PERMITUNITCAPQUANT            number(14, 3),
	PERMITUNITDETAILSEQNUMBER     number(3),
	PROCESSUNITCODE               varchar2(3 char),
	PROCESSUNITDATOWNRCODE        varchar2(2 char),
	PROCESSUNITTXT                varchar2(255 char),
	STANDARDPERMITIND             varchar2(1 char),
	SUPPINFTXT                    varchar2(2000 char),
	TRANSACTIONCODE               varchar2(1 char),
	PERMITUNITID                  number(19)
		CONSTRAINT FK_6CJGN1EGIX5L9ROBA185XYK00
		REFERENCES RCRA_PERMITUNIT
);

ALTER TABLE RCRA_HANDLERWASTECODE
	ADD CONSTRAINT FK_28A4OQQ5LEOOAJR9G5JMMBYJ1
FOREIGN KEY (PERMITUNITDETAILID) REFERENCES RCRA_PERMITUNITDETAIL;

ALTER TABLE RCRA_PERMITRELEVENT
	ADD CONSTRAINT FK_PXI25EFY21PMRS6JIQM1I15UK
FOREIGN KEY (PERMITUNITDETAILID) REFERENCES RCRA_PERMITUNITDETAIL;

CREATE TABLE RCRA_REQUEST
(
	ID                number(19) NOT NULL
		PRIMARY KEY,
	AGENCYTXT         varchar2(255 char),
	DATEOFREQUESTITEM date,
	DATERESPRECITEM   date,
	NOTES             varchar2(2000 char),
	REQUESTAGENCY     varchar2(1 char),
	REQUESTSEQNUMBER  number(6),
	TRANSACTIONCODE   varchar2(1 char),
	EVALID            number(19)
		CONSTRAINT FK_IK9YMTYQH8J2KXB61BS5QXMXG
		REFERENCES RCRA_EVAL
);

CREATE TABLE RCRA_SITEWASTEACT
(
	ID                          number(19) NOT NULL
		PRIMARY KEY,
	FURNACEEXEMPTIONCODE        varchar2(1 char),
	IMPORTERACTCODE             varchar2(1 char),
	LANDTYPECODE                varchar2(1 char),
	LANDTYPETXT                 varchar2(255 char),
	MIXEDWASTEGENRTRCODE        varchar2(1 char),
	ONSITEBURNEREXEMPTIONCODE   varchar2(1 char),
	RECOGNIZEDTRADEREXPORTERIND varchar2(1 char),
	RECOGNIZEDTRADERIMPORTERIND varchar2(1 char),
	RECYCLERACTCODE             varchar2(1 char),
	SHORTTERMGENRTRIND          varchar2(1 char),
	SLABEXPORTERIND             varchar2(1 char),
	SLABIMPORTERIND             varchar2(1 char),
	STATEDISTRICTCODE           varchar2(10 char),
	STATEDISTRICTCODETXT        varchar2(255 char),
	STATEDISTRICTOWNRNAME       varchar2(2 char),
	TRANSFERFACIND              varchar2(1 char),
	TRNSPRTRACTCODE             varchar2(1 char),
	TRTMNTSTORAGEDISPACTCODE    varchar2(1 char),
	UNDRGRNDINJECTIONACTCODE    varchar2(1 char),
	UNVWASTEDESTINATIONFACIND   varchar2(1 char)
);

ALTER TABLE RCRA_HANDLER
	ADD CONSTRAINT FK_44YSHGJ7BQF9R01LWHW5RN1WD
FOREIGN KEY (SITEWASTEACTID) REFERENCES RCRA_SITEWASTEACT;

CREATE TABLE RCRA_SOLICITHISTORY
(
	ID               number(19) NOT NULL
		PRIMARY KEY,
	SCHEDULERUNDATE  date,
	SOLICITTYPE      varchar2(255 char),
	PROCESSINGSTATUS varchar2(255 char),
	TRANSACTIONID    varchar2(255 char)
);

CREATE TABLE RCRA_STATEACT
(
	ID               number(19) NOT NULL
		PRIMARY KEY,
	STATEACTOWNRNAME varchar2(2 char),
	STATEACTTYPECODE varchar2(5 char),
	STATEACTTYPETXT  varchar2(255 char),
	TRANSACTIONCODE  varchar2(1 char),
	HANDLERID        number(19)
		CONSTRAINT FK_BSIUM76RWFIIB6N8200HU01BS
		REFERENCES RCRA_HANDLER
);

CREATE TABLE RCRA_SUPPENVPROJ
(
	ID                    number(19) NOT NULL
		PRIMARY KEY,
	SEPACTUALDATEITEM     date,
	SEPCODEOWNR           varchar2(2 char),
	SEPDEFAULTEDDATEITEM  date,
	SEPDESCTXT            varchar2(3 char),
	SEPEXPENDITUREAMT     number(13, 2),
	SEPLONGDESCTXT        varchar2(255 char),
	SEPSCHEDCMPLTDATEITEM date,
	SEPSEQNUMBER          number(2),
	NOTES                 varchar2(2000 char),
	TRANSACTIONCODE       varchar2(1 char),
	ENFRCACTID            number(19)
		CONSTRAINT FK_LSDJMG3I3IUMUGNM10MHQT1Q6
		REFERENCES RCRA_ENFRCACT
);

CREATE TABLE RCRA_UNVWASTEACT
(
	ID                   number(19) NOT NULL
		PRIMARY KEY,
	ACCUMULATEDWASTECODE varchar2(1 char),
	GENERATEDHANDLERCODE varchar2(1 char),
	TRANSACTIONCODE      varchar2(1 char),
	UNVWASTEOWNRNAME     varchar2(2 char),
	UNVWASTETYPECODE     varchar2(1 char),
	UNVWASTETYPETXT      varchar2(255 char),
	HANDLERID            number(19)
		CONSTRAINT FK_BXYQL2L905SX8WJIE01IARH33
		REFERENCES RCRA_HANDLER
);

CREATE TABLE RCRA_USEDOIL
(
	ID                        number(19) NOT NULL
		PRIMARY KEY,
	FUELBURNERCODE            varchar2(1 char),
	MARKETBURNERCODE          varchar2(1 char),
	PROCESSORCODE             varchar2(1 char),
	REFINERCODE               varchar2(1 char),
	SPECIFICATIONMARKETERCODE varchar2(1 char),
	TRANSFERFACCODE           varchar2(1 char),
	TRNSPRTRCODE              varchar2(1 char)
);

ALTER TABLE RCRA_HANDLER
	ADD CONSTRAINT FK_KAGVX3RFK4UYS281MAW3FPJWX
FOREIGN KEY (USEDOILID) REFERENCES RCRA_USEDOIL;

CREATE TABLE RCRA_VIO
(
	ID                    number(19) NOT NULL
		PRIMARY KEY,
	AGENCYTXT             varchar2(255 char),
	AGENCYDETERMVIO       varchar2(1 char),
	FORMERCITNNAME        varchar2(35 char),
	NOTES                 varchar2(2000 char),
	RETCOMPACTUALDATEITEM date,
	RETTOCOMPQUALIFIER    varchar2(1 char),
	RETTOCOMPQUALIFIERTXT varchar2(255 char),
	TRANSACTIONCODE       varchar2(1 char),
	VIOACTLOC             varchar2(2 char),
	VIODETERMDATEITEM     date,
	VIORSPAGENCY          varchar2(1 char),
	VIORSPAGENCYTXT       varchar2(255 char),
	VIOSEQNUMBER          number(4),
	VIOTYPE               varchar2(10 char),
	VIOTYPEOWNR           varchar2(2 char),
	VIOTYPETXT            varchar2(255 char),
	CMEFACSUBID           number(19)
		CONSTRAINT FK_NL8FONV908Q9BRGYI1AI98UQ2
		REFERENCES RCRA_CMEFACSUB
);

ALTER TABLE RCRA_CITN
	ADD CONSTRAINT FK_R27U7OLEP4IM3Y7KYVVH3KC93
FOREIGN KEY (VIOID) REFERENCES RCRA_VIO;

CREATE TABLE RCRA_VIOENFRC
(
	ID                   number(19) NOT NULL
		PRIMARY KEY,
	AGENCYTXT            varchar2(255 char),
	AGENCYDETERMVIO      varchar2(1 char),
	RETCOMPSCHEDDATEITEM date,
	TRANSACTIONCODE      varchar2(1 char),
	VIOSEQNUMBER         number(4),
	ENFRCACTID           number(19)
		CONSTRAINT FK_1QI1YI8DBDI6XV8PXBPID6MJI
		REFERENCES RCRA_ENFRCACT
);

CREATE TABLE RCRA_WASTEGENRTR
(
	ID                    number(19) NOT NULL
		PRIMARY KEY,
	WASTEGENRTROWNRNAME   varchar2(2 char),
	WASTEGENRTRSTATUSCODE varchar2(1 char),
	WASTEGENRTRSTATUSTXT  varchar2(255 char)
);

ALTER TABLE RCRA_HANDLER
	ADD CONSTRAINT FK_AIITOQI1PPJ37J2I5D3ON5TAT
FOREIGN KEY (WASTEGENRTRID) REFERENCES RCRA_WASTEGENRTR;

ALTER TABLE RCRA_HANDLER
	ADD CONSTRAINT FK_J6O819S62KF895FBTQOKWF488
FOREIGN KEY (STATEWASTEGENRTRID) REFERENCES RCRA_WASTEGENRTR;

CREATE TABLE RCRA_WHERETYPE
(
	SRS_DIM      number(19, 2),
	SRS_NAME     varchar2(255 char),
	SRSDIMENSION number(20),
	SRSNAME      varchar2(255 char),
	ID           number(19) NOT NULL
		PRIMARY KEY
		CONSTRAINT FK_MK80QQN3Y3L4CV62DV8K2XL2D
		REFERENCES RCRA_ABSFEATUREPROPTYPE
);

ALTER TABLE RCRA_GEOGINF
	ADD CONSTRAINT FK_EG9FDQA3HVK7NVW33W0PND3VQ
FOREIGN KEY (WHEREID) REFERENCES RCRA_WHERETYPE;

